apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-acos-discovery-gateway
  name: fint-flyt-acos-discovery-gateway
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-acos-discovery-gateway
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-acos-discovery-gateway
  labels:
    app: fint-flyt-acos-discovery-gateway
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`viken-no-skjema.vigoiks.no`) && PathPrefix(`/api/acos/metadata`)
      kind: Rule
      services:
        - name: fint-flyt-acos-discovery-gateway
          port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-acos-discovery-gateway
  name: fint-flyt-acos-discovery-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-acos-discovery-gateway
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-acos-discovery-gateway
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-acos-discovery-gateway:dummy
          name: fint-flyt-acos-discovery-gateway
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc' }
            - { name: fint.org-id, value: 'viken.no' }
            - { name: fint.flyt.resource-server.security.api.external.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.external.authorized-client-ids, value: '1' }