fint:
  application-id: fint-flyt-acos-discovery-gateway

server:
  error:
    include-message: always

spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-web-resource-server

  output:
    ansi:
      enabled: always
