apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-acos-discovery-gateway_vlfk_no
  fintlabs.no/org-id: vlfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/alpha/vlfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/alpha/vlfk-no/api/acos/metadata"

    target:
      kind: Application
      name: fint-flyt-acos-discovery-gateway

